#!/usr/bin/env bash
#
# build.sh — assemble and build the Arch Silverblue ISO with archiso/mkarchiso.
#
# Runs inside the container defined by iso/Dockerfile (Arch, root, --privileged). It starts
# from the official `releng` profile, overlays our airootfs, injects the Silverblue tools at
# their final paths, builds a synthetic local pacman repo (for the hermetic update test), and
# invokes mkarchiso. The finished ISO lands in iso/output/.
set -euo pipefail

REPO=${SB_REPO_DIR:-/build}
PROFILE=${SB_PROFILE_DIR:-/tmp/silverblue-profile}
WORK=${SB_WORK_DIR:-/tmp/archiso-work}
OUT="$REPO/iso/output"
RELENG=${SB_RELENG_DIR:-/usr/share/archiso/configs/releng}

log() { printf '[build] %s\n' "$*"; }

# --- Load the derived-distro configuration (single source of truth) ------------------------
CONF=${SB_DISTRO_CONF:-$REPO/config/distro.conf}
[[ -f "$CONF" ]] || { printf '[build] missing config: %s\n' "$CONF" >&2; exit 1; }
# shellcheck source=../config/distro.conf
source "$CONF"

# Escape a string for the replacement side of a sed 's|...|...|' command.
esc() { printf '%s' "$1" | sed -e 's/[\\&|]/\\&/g'; }

# Rewrite stdin->stdout, replacing the upstream "silverblue" identifiers and branding with the
# values from config/distro.conf: lowercase identifiers are renamed by prefix, "Arch Silverblue"
# becomes $DISTRO_NAME, and the docs URL is swapped. Uppercase SILVERBLUE-* markers are left
# untouched (the QEMU harness greps them); the engine is installed verbatim with baked config
# (see below) rather than rendered.
render() {
    sed -e "s|/usr/lib/silverblue|$(esc "$LIB_DIR")|g" \
        -e "s|silverblue-update|$(esc "$BIN_PREFIX")-update|g" \
        -e "s|silverblue-mark-good|$(esc "$UNIT_PREFIX")-mark-good|g" \
        -e "s|silverblue-rollback|$(esc "$UNIT_PREFIX")-rollback|g" \
        -e "s|silverblue-watchdog|$(esc "$UNIT_PREFIX")-watchdog|g" \
        -e "s|https://github.com/sinisterMage/Arch-silverblue|$(esc "$DISTRO_HOME_URL")|g" \
        -e "s|Arch Silverblue|$(esc "$DISTRO_NAME")|g"
}

require() {
    command -v "$1" >/dev/null 2>&1 || { printf 'missing tool: %s\n' "$1" >&2; exit 1; }
}

# --- Build a minimal pacman package (.PKGINFO + payload) without makepkg -------------------
# Args: name version arch destdir
make_pkg() {
    local name=$1 ver=$2 arch=$3 dest=$4
    local root
    root=$(mktemp -d)
    mkdir -p "$root/etc"
    printf '%s version %s\n' "$name" "$ver" > "$root/etc/silverblue-marker"
    {
        printf 'pkgname = %s\n' "$name"
        printf 'pkgver = %s-1\n' "$ver"
        printf 'pkgdesc = Arch Silverblue test marker package\n'
        printf 'arch = %s\n' "$arch"
        printf 'builddate = 0\n'
        printf 'size = 32\n'
    } > "$root/.PKGINFO"
    ( cd "$root" && bsdtar --zstd -cf "$dest/${name}-${ver}-1-${arch}.pkg.tar.zst" .PKGINFO etc )
    rm -rf "$root"
}

main() {
    require mkarchiso
    require bsdtar
    require repo-add

    log "Preparing profile from $RELENG"
    rm -rf "$PROFILE"
    cp -r "$RELENG" "$PROFILE"

    log "Overlaying iso/airootfs"
    cp -rT "$REPO/iso/airootfs" "$PROFILE/airootfs"

    # Name the ISO after the distro id (releng defaults to archlinux-*.iso), so releases
    # and derivatives ship a recognizable file name.
    sed -i "s|^iso_name=.*|iso_name=\"${DISTRO_ID}\"|" "$PROFILE/profiledef.sh"

    # Multilib (lib32) for derivatives that need it (ENABLE_MULTILIB=1 in distro.conf):
    # uncomment the [multilib] section releng ships commented out. The profile pacman.conf
    # becomes the live ISO's /etc/pacman.conf, which pacstrap uses for the target.
    if [[ "${ENABLE_MULTILIB:-0}" == 1 ]]; then
        log "Enabling [multilib] in the live pacman.conf"
        sed -i '/^#\[multilib\]/,/^#Include/ s/^#//' "$PROFILE/pacman.conf"
        if ! grep -q '^\[multilib\]' "$PROFILE/pacman.conf"; then
            printf '\n[multilib]\nInclude = /etc/pacman.d/mirrorlist\n' >> "$PROFILE/pacman.conf"
        fi
    fi

    # --- Inject the distro tools at their installed paths (renamed/rendered per config) ----
    log "Injecting tools (bin=${BIN_PREFIX}-update lib=${LIB_DIR})"
    local A="$PROFILE/airootfs"
    install -d "$A/usr/bin" "$A${LIB_DIR}" "$A/usr/lib/systemd/system" "$A/etc/systemd/system.conf.d"

    # Engine: install verbatim, then prepend baked config so the installed copy defaults to this
    # distro's identity in every context (interactive CLI, the mark-good service that *sources*
    # it, and rollback.sh that exec's it) with no runtime config plumbing. printf %q keeps the
    # values safe to re-source; the engine's own ': "${SB_X:=default}"' lines run afterwards and
    # keep these baked values.
    local eng="$A/usr/bin/${BIN_PREFIX}-update"
    {
        head -n 1 "$REPO/src/update-engine/silverblue-update"
        printf '# --- Baked distro config (generated by build.sh from config/distro.conf) ---\n'
        printf 'SB_LIB_DIR=%q\n'      "$LIB_DIR"
        printf 'SB_VERIFY_UNIT=%q\n'  "/usr/lib/systemd/system/${UNIT_PREFIX}-mark-good.service"
        printf 'SB_TOPLEVEL_MNT=%q\n' "$TOPLEVEL_MNT"
        printf 'SB_EFI_DIR=%q\n'      "$EFI_DIR"
        printf 'SB_KEEP=%q\n'         "$KEEP_SNAPSHOTS"
        printf 'SB_TRIES=%q\n'        "$BOOT_TRIES"
        printf 'SB_DISTRO_NAME=%q\n'  "$DISTRO_NAME"
        printf 'SB_ESP_SUBDIR=%q\n'   "$ESP_SUBDIR"
        printf 'SB_SORT_KEY=%q\n'     "$SORT_KEY"
        tail -n +2 "$REPO/src/update-engine/silverblue-update"
    } > "$eng"
    chmod 0755 "$eng"

    # Bootloader helpers: installed verbatim (they read the engine-provided SB_* vars at runtime).
    install -Dm0644 "$REPO/src/bootloader/sdboot-helpers.sh" "$A${LIB_DIR}/sdboot-helpers.sh"
    install -Dm0644 "$REPO/src/bootloader/grub-helpers.sh"   "$A${LIB_DIR}/grub-helpers.sh"

    # Installer: shared library + interactive frontend. Both source config/distro.conf at
    # runtime, so they are installed verbatim — only the frontend's *name* is derived. The
    # library lives at a fixed, id-independent path both frontends default to.
    install -Dm0644 "$REPO/src/installer/install-lib.sh" "$A/usr/local/lib/installer/install-lib.sh"
    install -Dm0755 "$REPO/src/installer/silverblue-install" "$A/usr/bin/${BIN_PREFIX}-install"

    # Init scripts + units: renamed by prefix and rendered (paths/branding substituted).
    render < "$REPO/src/init/silverblue-mark-good.sh" > "$A${LIB_DIR}/${UNIT_PREFIX}-mark-good.sh"
    render < "$REPO/src/init/silverblue-rollback.sh"  > "$A${LIB_DIR}/${UNIT_PREFIX}-rollback.sh"
    chmod 0755 "$A${LIB_DIR}/${UNIT_PREFIX}-mark-good.sh" "$A${LIB_DIR}/${UNIT_PREFIX}-rollback.sh"
    render < "$REPO/src/init/silverblue-mark-good.service" > "$A/usr/lib/systemd/system/${UNIT_PREFIX}-mark-good.service"
    render < "$REPO/src/init/silverblue-rollback.service"  > "$A/usr/lib/systemd/system/${UNIT_PREFIX}-rollback.service"
    render < "$REPO/src/init/silverblue-rollback.target"   > "$A/usr/lib/systemd/system/${UNIT_PREFIX}-rollback.target"
    render < "$REPO/src/init/silverblue-watchdog.conf"     > "$A/etc/systemd/system.conf.d/${UNIT_PREFIX}-watchdog.conf"
    chmod 0755 "$A/usr/local/bin/silverblue-autoinstall.sh" \
        "$A/usr/local/bin/silverdeck-live-session" "$A/usr/local/bin/silverdeck-installer-run"

    # The autoinstaller reads config/distro.conf at install time; ship it (+ the os-release
    # template) at a fixed, id-independent path it can always find.
    install -Dm0644 "$CONF" "$A/usr/local/share/distro/distro.conf"
    install -Dm0644 "$REPO/config/os-release.in" "$A/usr/local/share/distro/os-release.in"

    # Ensure the executables are 0755 in the live ISO. mkarchiso applies file_permissions from
    # profiledef.sh; without an entry it may normalize files to 0644 (which would make the
    # enabled mark-good.service fail to exec). Inject entries (built from config) after the
    # array's opening line via sed's 'r' command (reads a file, so no \n-escaping headaches).
    local fp; fp=$(mktemp)
    {
        printf '  ["/usr/bin/%s-update"]="0:0:755"\n'   "$BIN_PREFIX"
        printf '  ["/usr/bin/%s-install"]="0:0:755"\n'  "$BIN_PREFIX"
        printf '  ["%s/%s-mark-good.sh"]="0:0:755"\n'   "$LIB_DIR" "$UNIT_PREFIX"
        printf '  ["%s/%s-rollback.sh"]="0:0:755"\n'    "$LIB_DIR" "$UNIT_PREFIX"
        printf '  ["/usr/local/bin/silverblue-autoinstall.sh"]="0:0:755"\n'
        printf '  ["/usr/local/bin/silverdeck-live-session"]="0:0:755"\n'
        printf '  ["/usr/local/bin/silverdeck-installer-run"]="0:0:755"\n'
    } > "$fp"
    sed -i "/^file_permissions=(/r $fp" "$PROFILE/profiledef.sh"
    rm -f "$fp"

    # Live-ISO greeting pointing at the interactive installer (overrides releng's motd).
    printf 'Welcome to %s live.\n\nTo install to disk, run: %s-install\n\n' \
        "$DISTRO_NAME" "$BIN_PREFIX" > "$A/etc/motd"

    # --- Enable services in the live ISO --------------------------------------------------
    log "Enabling services"
    mkdir -p "$A/etc/systemd/system/multi-user.target.wants"
    ln -sf "/usr/lib/systemd/system/${UNIT_PREFIX}-mark-good.service" \
        "$A/etc/systemd/system/multi-user.target.wants/${UNIT_PREFIX}-mark-good.service"
    # The autoinstaller is driven by the QEMU harness over the serial autologin shell, so it
    # is NOT auto-enabled here (its service file remains for the optional fw_cfg-driven path).

    # --- Synthetic local package repo for the hermetic update test ------------------------
    log "Building synthetic local repo (silverblue-marker 1 -> 2)"
    local instdir="$A/opt/silverblue/install" repodir="$A/opt/silverblue/localrepo"
    mkdir -p "$instdir" "$repodir"
    make_pkg silverblue-marker 1 any "$instdir"
    make_pkg silverblue-marker 2 any "$repodir"
    ( cd "$repodir" && repo-add silverblue-local.db.tar.gz ./*.pkg.tar.zst >/dev/null )

    # --- Derivative package repo (real packages, e.g. the SilverDeck UI/session) ----------
    # A pacman repo prebuilt at iso/local-repo (see packaging/build-repo.sh in the
    # derivative's tree) is baked into the ISO; the installer registers it in the live
    # pacman.conf for pacstrap and copies it onto the target (install-lib.sh).
    local localrepo="$REPO/iso/local-repo"
    if [[ -d "$localrepo" ]]; then
        log "Baking derivative package repo (/opt/${DISTRO_ID}/repo)"
        mkdir -p "$A/opt/${DISTRO_ID}"
        cp -a "$localrepo" "$A/opt/${DISTRO_ID}/repo"
    elif printf '%s\n' "${PKGS_BASE[@]}" | grep -q "^${DISTRO_ID}-"; then
        printf '[build] PKGS_BASE references %s-* packages but %s is missing (build it first)\n' \
            "$DISTRO_ID" "$localrepo" >&2
        exit 1
    fi

    # --- Live GUI installer session (LIVE_GUI_SESSION=1 in distro.conf) -------------------
    # Boots the live ISO into greetd -> sway -> the GUI installer. The session
    # configs ship in iso/airootfs (inert without these packages/symlinks).
    if [[ "${LIVE_GUI_SESSION:-0}" == 1 ]]; then
        log "Enabling the live GUI installer session"
        if [[ ! -d "$localrepo" ]]; then
            printf '[build] LIVE_GUI_SESSION=1 needs the derivative repo at %s (build it first)\n' \
                "$localrepo" >&2
            exit 1
        fi
        # mkarchiso's pacstrap resolves packages against the profile pacman.conf on the
        # BUILD side, and the live system reuses that file at runtime — so register the
        # baked repo once, at a path that exists in both worlds: stage a copy at
        # /opt/${DISTRO_ID}/repo in the build container (the airootfs bake above already
        # put it there for the live system).
        mkdir -p "/opt/${DISTRO_ID}"
        rm -rf "/opt/${DISTRO_ID}/repo"
        cp -a "$localrepo" "/opt/${DISTRO_ID}/repo"
        if ! grep -qxF "[${DISTRO_ID}]" "$PROFILE/pacman.conf"; then
            printf '\n[%s]\nSigLevel = Optional TrustAll\nServer = file:///opt/%s/repo\n' \
                "$DISTRO_ID" "$DISTRO_ID" >> "$PROFILE/pacman.conf"
        fi
        # GUI session packages (greetd/sway/installer/...) on the live medium.
        printf '%s\n' "${PKGS_ISO_GUI[@]}" >> "$PROFILE/packages.x86_64"
        # Boot to the kiosk: graphical.target, greetd, NetworkManager. Drop releng's
        # iwd/systemd-networkd enablement so only one stack manages the network (the
        # symlink names track upstream releng; rm -f keeps this tolerant of drift).
        ln -sf /usr/lib/systemd/system/graphical.target "$A/etc/systemd/system/default.target"
        mkdir -p "$A/etc/systemd/system/graphical.target.wants" \
                 "$A/etc/systemd/system/multi-user.target.wants" \
                 "$A/etc/systemd/system/getty.target.wants"
        ln -sf /usr/lib/systemd/system/greetd.service \
            "$A/etc/systemd/system/graphical.target.wants/greetd.service"
        ln -sf /usr/lib/systemd/system/NetworkManager.service \
            "$A/etc/systemd/system/multi-user.target.wants/NetworkManager.service"
        rm -f "$A/etc/systemd/system/multi-user.target.wants/iwd.service" \
              "$A/etc/systemd/system/multi-user.target.wants/systemd-networkd.service" \
              "$A/etc/systemd/system/network-online.target.wants/systemd-networkd-wait-online.service" \
              "$A/etc/systemd/system/sockets.target.wants/systemd-networkd.socket" \
              "$A/etc/systemd/system/dbus-org.freedesktop.network1.service"
        # A console survives on VT2 (greetd owns VT1; serial getty is untouched, so the
        # QEMU harness contract holds).
        ln -sf /usr/lib/systemd/system/getty@.service \
            "$A/etc/systemd/system/getty.target.wants/getty@tty2.service"
        # Live greeting reflecting the GUI-first flow.
        printf 'Welcome to %s live.\n\nThe graphical installer runs on the display (VT1).\nThis console: text installer via %s-install, or just look around.\n\n' \
            "$DISTRO_NAME" "$BIN_PREFIX" > "$A/etc/motd"
    fi

    # --- Extra packages needed by the autoinstaller ---------------------------------------
    log "Adding packages to the ISO package list"
    printf '%s\n' "${PKGS_ISO[@]}" >> "$PROFILE/packages.x86_64"
    sort -u -o "$PROFILE/packages.x86_64" "$PROFILE/packages.x86_64"

    # --- Serial console on the live ISO ---------------------------------------------------
    # The headless QEMU harness reads the install over the serial port, so the live boot must
    # log to ttyS0. (The installed target sets this itself in its own boot entry.)
    log "Adding serial console to ISO boot entries"
    local f
    while IFS= read -r -d '' f; do
        sed -i -E 's|^(options[[:space:]].*)$|\1 console=ttyS0,115200 console=tty0|' "$f"
    done < <(find "$PROFILE" -path '*loader/entries/*.conf' -type f -print0)
    if [[ -d "$PROFILE/syslinux" ]]; then
        find "$PROFILE/syslinux" -name '*.cfg' -type f -exec \
            sed -i -E 's|^([[:space:]]*APPEND .*)$|\1 console=ttyS0,115200 console=tty0|' {} + || true
    fi

    # --- Build -----------------------------------------------------------------------------
    mkdir -p "$OUT" "$WORK"
    log "Running mkarchiso (this downloads packages; needs network + --privileged)"
    mkarchiso -v -w "$WORK" -o "$OUT" "$PROFILE"

    # Publish checksums alongside the ISO(s) so downloads can be verified
    # (`sha256sum -c SHA256SUMS`). Names are stored relative to $OUT.
    log "Generating SHA256SUMS"
    ( cd "$OUT" && sha256sum ./*.iso > SHA256SUMS )

    # The container runs as root, so the artifacts land root-owned on the bind-mounted
    # checkout; hand them back to the repo owner so host-side steps (the Makefile's stamp
    # file, `make clean`, CI artifact upload) can manage them without root.
    chown -R --reference="$REPO" "$OUT"

    log "Done. ISO(s):"
    ls -lh "$OUT"/*.iso "$OUT"/SHA256SUMS
}

main "$@"
