# shellcheck shell=bash
#
# grub-helpers.sh — GRUB integration for Arch Silverblue.
#
# Sourced by src/update-engine/silverblue-update and src/init/silverblue-mark-good.sh.
# Pure render/predicate functions are self-contained and safe to source for unit tests.
# IO functions rely on log()/sb_run()/emit_file() provided by the sourcing engine.
#
# GRUB can READ Btrfs natively, so menuentries point straight at each snapshot's /boot
# inside the subvolume (no kernel copying). GRUB can NOT WRITE Btrfs, so the writable
# grubenv lives on the FAT ESP ($EFI/grub/grubenv) and grub.cfg loads it from there.
#
# Next-boot-without-changing-default uses the one-shot `next_entry`; auto-rollback uses
# the `recordfail` tripwire: grub.cfg arms it on the one-shot boot and mark-good clears it,
# so a boot that never marks good leaves `saved_entry` (the old root) as the default on
# the next (e.g. watchdog-reset or rollback-service) boot. recordfail keeps a FINITE menu
# timeout: an unattended machine must keep booting the default, never hold the menu.
#
# Known GRUB limitation (unlike systemd-boot's boot counting): a kernel that fails to
# LOAD leaves GRUB waiting at "Press any key"/the menu — stock GRUB has no unattended
# in-session fallback (its `fallback` variable only accepts numeric entry indexes and
# does not chain from an interactive selection). The previous root is one keypress away
# on the held menu; health-check failures and hangs still roll back automatically.

# Return 0 if GRUB appears to be the active bootloader under $1 (the ESP mount).
grub_is_active() {
    local efi=$1
    [[ -f "$efi/grub/grub.cfg" ]] && return 0
    [[ -e "$efi/EFI/GRUB/grubx64.efi" || -e "$efi/EFI/grub/grubx64.efi" ]] && return 0
    return 1
}

# Render a single menuentry to stdout. Pure: no IO.
# Kernels are read from <pool-top-level>/<snap>/boot via Btrfs, so paths are subvol-relative
# to the filesystem root that `search` selects.
#   $1 snap   $2 label   $3 pool_uuid
grub_render_menuentry() {
    local snap=$1 label=$2 uuid=$3
    cat <<EOF
menuentry '$label' --id $snap {
    insmod btrfs
    insmod part_gpt
    search --no-floppy --fs-uuid --set=root $uuid
    linux  /$snap/boot/vmlinuz-linux root=UUID=$uuid rootflags=subvol=$snap rootfstype=btrfs rw${SB_KERNEL_OPTS:+ $SB_KERNEL_OPTS}
    initrd /$snap/boot/initramfs-linux.img
}
EOF
}

# Render the grub.cfg header: load grubenv from the FAT ESP, consume the one-shot
# `next_entry` (arming `recordfail`), otherwise boot the permanent `saved_entry`.
grub_render_header() {
    local timeout=${1:-5}
    cat <<EOF
# Generated by silverblue-update. Do not edit by hand.
load_env --file \${prefix}/grubenv
set default="0"
if [ -n "\${saved_entry}" ]; then set default="\${saved_entry}"; fi
if [ -n "\${next_entry}" ]; then
    set default="\${next_entry}"
    set next_entry=
    save_env --file \${prefix}/grubenv next_entry
    set recordfail=1
    save_env --file \${prefix}/grubenv recordfail
fi
if [ "\${recordfail}" = 1 ]; then set timeout=10; else set timeout=$timeout; fi
EOF
}

# Regenerate grub.cfg from the current snapshot set. Each argument is a "snap|label" pair,
# newest last. grubenv lives next to grub.cfg on the ESP.
#   $1 efi_dir   $2 pool_uuid   $3.. snap|label pairs
grub_regen_cfg() {
    local efi=$1 uuid=$2
    shift 2
    local grub_dir="$efi/grub" pair snap label
    sb_run mkdir -p "$grub_dir"
    {
        grub_render_header 5
        for pair in "$@"; do
            snap=${pair%%|*}
            label=${pair#*|}
            printf '\n'
            grub_render_menuentry "$snap" "$label" "$uuid"
        done
    } | emit_file "$grub_dir/grub.cfg"
}

# Point the next boot at a snapshot via the one-shot next_entry (default unchanged).
#   $1 snap   $2 efi_dir
grub_set_next() {
    local snap=$1 efi=$2
    sb_run "$GRUB_EDITENV" "$efi/grub/grubenv" set "next_entry=$snap"
}

# Mark the current snapshot good: make it the permanent saved_entry and disarm recordfail.
#   $1 snap   $2 efi_dir
grub_mark_good() {
    local snap=$1 efi=$2
    local env="$efi/grub/grubenv"
    sb_run "$GRUB_EDITENV" "$env" set "saved_entry=$snap"
    sb_run "$GRUB_EDITENV" "$env" set "boot_success=1"
    sb_run "$GRUB_EDITENV" "$env" unset recordfail
}

# Pruning is handled by regenerating grub.cfg without the dropped snapshot; nothing to copy
# out means nothing to delete from the ESP beyond the regenerated config.
grub_prune_entry() {
    : "${1:?snap}" "${2:?efi}"
    return 0
}
